name: wtracker
description: "weight-tracker"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Utils
  uuid: ^4.4.0
  
  # Localizations
  intl: ^0.19.0
  slang: ^3.26.1
  slang_flutter: ^3.26.1

  # Model serialization
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

  # DI
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  # State managemnet
  flutter_bloc: ^8.1.5

  # db
  shared_preferences: ^2.2.3

  # ui
  fl_chart: ^0.68.0

  # internet
  chopper: ^8.0.0
  go_router: ^14.2.0
  shimmer: ^3.0.0
  json_annotation: ^4.9.0
  email_validator: ^2.1.17
  share_plus: ^9.0.0
  flutter_native_splash: ^2.4.0
  package_info_plus: ^8.0.0

dev_dependencies:
  drift_dev: ^2.18.0
  build_runner: ^2.4.9

  chopper_generator: ^8.0.0
  riverpod_generator: ^2.4.0

  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true