name: wtracket
description: "weight tracker app"

publish_to: 'none' 


version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  logger: ^2.2.0

  # Localizations
  intl: ^0.17.0
  slang: ^3.26.1
  slang_flutter: ^3.26.1
  
  # Navigation
  go_router: ^10.0.0

  # Ui
  balanced_text: ^0.0.3
  shimmer_effect: ^1.0.4

  # DI
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1

  # State managemnet
  flutter_bloc: ^8.1.5

  # Model serialization
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

  # Api
  chopper: ^7.4.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_hooks: ^0.20.5

  # Validators
  email_validator: ^2.1.17
  json_annotation: ^4.9.0
  
  # Features
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  flutter_native_splash: ^2.3.2
  package_info_plus: ^8.0.0

  loading_animation_widget: ^1.2.1

dev_dependencies:
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner: ^2.4.9
  chopper_generator: ^7.4.0

  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true